// Generated by CoffeeScript 1.7.1
(function() {
  describe("Base View", function() {
    return describe("new()", function() {
      beforeEach(function() {
        return loadFixtures("/views/base.html");
      });
      it("can be initialized with a dom element id", function() {
        var baseView;
        baseView = new App.Views.Base({
          id: "base-view-id"
        });
        expect(baseView.id).toBe("base-view-id");
        return expect(baseView.domElement).toEqual($("#base-view-id"));
      });
      return it("can be initialized with a dom element", function() {
        var baseView;
        baseView = new App.Views.Base({
          domElement: $("#base-view-id")
        });
        expect(baseView.id).toBe("base-view-id");
        return expect(baseView.domElement).toEqual($("#base-view-id"));
      });
    });
  });

}).call(this);
