// Generated by CoffeeScript 1.7.1
(function() {
  describe("Base View", function() {
    beforeEach(function() {
      return loadFixtures("/views/base.html");
    });
    describe("new()", function() {
      it("can be initialized with a dom element id", function() {
        var baseView;
        baseView = new App.Views.Base({
          id: "parent-base-view"
        });
        expect(baseView.id).toBe("parent-base-view");
        return expect(baseView.domElement).toEqual($("#parent-base-view"));
      });
      return it("can be initialized with a dom element", function() {
        var baseView;
        baseView = new App.Views.Base({
          domElement: $("#parent-base-view")
        });
        expect(baseView.id).toBe("parent-base-view");
        return expect(baseView.domElement).toEqual($("#parent-base-view"));
      });
    });
    return describe("findAll()", function() {
      it("finds all App.Views.Base objects in the DOM", function() {
        var baseViews;
        baseViews = App.Views.Base.findAll();
        return expect(baseViews.length).toBe(4);
      });
      return it("finds only App.Views.Base objects within a specified DOM context", function() {
        var baseViews, parentBaseView;
        parentBaseView = new App.Views.Base({
          id: "parent-base-view"
        });
        baseViews = App.Views.Base.findAll(parentBaseView.domElement);
        return expect(baseViews.length).toBe(3);
      });
    });
  });

}).call(this);
