// Generated by CoffeeScript 1.7.1
(function() {
  describe("Checkbox View", function() {
    beforeEach(function() {
      return loadFixtures("/views/checkbox.html");
    });
    return describe("_attachBehavior()", function() {
      var checkbox;
      checkbox = {};
      beforeEach(function() {
        checkbox = new App.Views.Checkbox({
          id: "checkbox-id"
        });
        return spyOnEvent('#checkbox-id', 'click');
      });
      return it("prevents click events from firing in parent elements", function() {
        checkbox.domElement.click();
        return expect('click').toHaveBeenStoppedOn('#checkbox-id');
      });
    });
  });

}).call(this);
